# Generated by Django 2.2.1 on 2019-05-16 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('0', 'superuser'), ('1', 'partner'), ('2', 'credit_organization')], default='0', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('date_birth', models.DateField()),
                ('passport_number', models.CharField(max_length=15)),
                ('score', models.PositiveIntegerField()),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_customer', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credituser', to='credit.CreditUser')),
            ],
        ),
        migrations.CreateModel(
            name='CreditProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('rotation_start', models.DateTimeField()),
                ('rotation_end', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
                ('credit_type', models.CharField(choices=[('0', 'consumption'), ('1', 'mortgage'), ('2', 'car')], default='0', max_length=50)),
                ('min_score', models.PositiveIntegerField()),
                ('max_score', models.PositiveIntegerField()),
                ('credit_agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_agency', to='credit.CreditUser')),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('sent_on', models.DateTimeField(default=None, null=True)),
                ('status', models.CharField(choices=[('0', 'new'), ('1', 'sent'), ('2', 'recieved'), ('3', 'approved'), ('4', 'refused'), ('5', 'issued')], default='0', max_length=20)),
                ('credit_proposal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_proposal', to='credit.CreditProposal')),
                ('customer_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to='credit.CustomerProfile')),
            ],
        ),
    ]
